### ISSUE TITLE
'HttpResponse' object has no attribute 'render'

### ISSUE THREAD

**Issue by rosscdh** [moorinteractive/wagtail-bakery#13]
Hi there,
    Firstly, GREAT app and exactly what I had in mind with wagtail! Thank you.

Just found a small "bug" with the build management command when a content object returns an HttpResponse object that has already rendered

**bakery/views/base.py**
```
self.get(self.request).render().content
```
throws
```
AttributeError: 'HttpResponse' object has no attribute 'render'
```

The "fix" on my side was to

```
        resp = self.get(self.request)

        if hasattr(resp, 'render'):
            return resp.render().content
        elif hasattr(resp, 'content'):
            return resp.content
        else:
            raise Exception('Response has no content')
```

Which is a little ugly especially in the else case..  but I was just wanting to "make it work" on my side.

settings

```
BAKERY_MULTISITE = True

BAKERY_VIEWS = (
    'wagtailbakery.views.AllPublishedPagesView',
)
BUILD_DIR = '/tmp/asset-manager-build/'

```

**Comment by robmoorman** [comment]
Hi @rosscdh thanks!

We ran also into the same issue, we will provide a fix on very short notice (and first pypi version).
Please feel free to report any other suggestions and/or issues.

Do you have an example site which now runs with this module, just curious :).

Cheers

**Comment by rosscdh** [comment]
Hey there not at the moment, but we are working on it ;)

I have to say I've been doing cms systems for many years 15 or so.. and
wagtail is.. by far and away the best.

And bakery is exactly what I've had in mind. Thanks again!

**Comment by robmoorman** [comment]
Just ran into this issue again with ``HttpResponseRedirect`` response objects.
Probably you use ``render_to_response`` or ``render`` shortcuts in your Wagtail page.
Will provide a fix for this!

**Comment by rosscdh** [comment]
Thanks.. Happy to do a PR or take a note :)

**Comment by robmoorman** [comment]
Master should now work fine!
