### ISSUE TITLE
NotImplementedError: Complex filters with double-underscore clauses are not implemented yet

### ISSUE THREAD

**Issue by abadger1406** [moorinteractive/wagtail-bakery#18]
If you try clicking preview on a location page, you see this error.
![screenshot from 2017-05-13 23-48-49](https://cloud.githubusercontent.com/assets/634924/26029842/1105d41c-3837-11e7-80a9-30a6eb665403.png)

**Comment by robmoorman** [comment]
Hi @abadger1406 it seems it's not the ``wagtail-bakery`` module but an exception within the ``bakerydemo``.
